apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-deployment
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - name: frontend-deployment
        image: suchetasodage/frontend-deployment:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: httpd
          protocol: TCP
          containerPort: 80
