apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-deployment
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
      - name: backend-deployment
        image: suchetasodage/backend-deployment:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: tomcat
          protocol: TCP
          containerPort: 8080