apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  #replicas: 2
  selector:
    matchLabels:
      app: backend-deployment
  #strategy: 
    #type: RollingUpdate
    #rollingUpdate:
      #maxUnavailable: 1
      #maxSurge: 1
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
      - name: backend-deployment
        image: suchetasodage/k8s:backend
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: httpd
          protocol: TCP
          containerPort: 80